# Generated by Django 2.0.5 on 2018-11-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=34, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmainphoto',
            name='group_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object.GroupPhoto'),
        ),
        migrations.AlterField(
            model_name='postchat',
            name='uuid',
            field=models.CharField(default='a13fd522c0e940d0892d70bc350c7448', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchatrestmessage',
            name='uuid',
            field=models.CharField(default='a936ac2458d341219ea038e36c24876e', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='fafebd497b914e438bf2a98ac933e24e', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='solomainphoto',
            name='solo_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object.SoloPhoto'),
        ),
    ]
