# Generated by Django 2.0.5 on 2018-11-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_auto_20181102_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='postchat',
            name='uuid',
            field=models.CharField(default='5c0ac55036f74d70abe2c6d11dd5bc3e', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchatrestmessage',
            name='uuid',
            field=models.CharField(default='0e00ec9228484de0b3cad2645f2c70a4', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='5a4c5be14c9c44a582dc01ac1798c95a', max_length=34, unique=True),
        ),
    ]
