# Generated by Django 2.0.5 on 2018-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_auto_20181102_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchat',
            name='uuid',
            field=models.CharField(default='b7d0c2a4bc3746b893b5c090bb99de7b', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchatrestmessage',
            name='uuid',
            field=models.CharField(default='ce04ff64ea8a4b7c986da389421cfe6c', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='d4ddd579a48b4de98652831e7663d7e5', max_length=34, unique=True),
        ),
    ]
