# Generated by Django 2.0.5 on 2018-11-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_auto_20181107_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postchat',
            name='uuid',
            field=models.CharField(default='3e70a3bfa6bf4ce5ac24421731731f34', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postchatrestmessage',
            name='uuid',
            field=models.CharField(default='0cada26b814b4fb08834980223d00fbb', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='465a9a526bce4e0c9c8ae3c1fd56d0af', max_length=34, unique=True),
        ),
        migrations.AlterField(
            model_name='testdecimal',
            name='decimal_10',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
