# Generated by Django 2.0.5 on 2018-11-08 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0002_auto_20181108_2251'),
        ('object', '0007_auto_20181108_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('uuid', models.CharField(blank=True, default=None, max_length=34, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupDatePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object.Group')),
            ],
        ),
        migrations.CreateModel(
            name='PayLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=None, max_length=34, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoloDatePay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('solo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object.Solo')),
            ],
        ),
        migrations.RemoveField(
            model_name='postchat',
            name='before',
        ),
        migrations.RemoveField(
            model_name='postchat',
            name='post',
        ),
        migrations.AlterUniqueTogether(
            name='postchatlike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='postchatlike',
            name='post_chat',
        ),
        migrations.RemoveField(
            model_name='postchatlike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postchatlikecount',
            name='post_chat',
        ),
        migrations.AlterUniqueTogether(
            name='postchatread',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='postchatread',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postchatread',
            name='post_chat',
        ),
        migrations.RemoveField(
            model_name='postchatread',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postchatrestmessage',
            name='post_chat',
        ),
        migrations.RemoveField(
            model_name='postchatrestmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postchatrestmessagecount',
            name='post_chat',
        ),
        migrations.AlterUniqueTogether(
            name='postchatrestmessagelike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='postchatrestmessagelike',
            name='post_chat_rest_message',
        ),
        migrations.RemoveField(
            model_name='postchatrestmessagelike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postchatrestmessagelikecount',
            name='post_chat_rest_message',
        ),
        migrations.RemoveField(
            model_name='postchattext',
            name='post_chat',
        ),
        migrations.RemoveField(
            model_name='postfirstcheck',
            name='post',
        ),
        migrations.AlterUniqueTogether(
            name='postfollow',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='postfollow',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postfollow',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postfollowcount',
            name='post',
        ),
        migrations.DeleteModel(
            name='TestDecimal',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='has_another_profile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_chat_created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='charge',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='0593b29ec89d4b7183c6e87af808182d', max_length=34, unique=True),
        ),
        migrations.DeleteModel(
            name='PostChat',
        ),
        migrations.DeleteModel(
            name='PostChatLike',
        ),
        migrations.DeleteModel(
            name='PostChatLikeCount',
        ),
        migrations.DeleteModel(
            name='PostChatRead',
        ),
        migrations.DeleteModel(
            name='PostChatRestMessage',
        ),
        migrations.DeleteModel(
            name='PostChatRestMessageCount',
        ),
        migrations.DeleteModel(
            name='PostChatRestMessageLike',
        ),
        migrations.DeleteModel(
            name='PostChatRestMessageLikeCount',
        ),
        migrations.DeleteModel(
            name='PostChatText',
        ),
        migrations.DeleteModel(
            name='PostFirstCheck',
        ),
        migrations.DeleteModel(
            name='PostFollow',
        ),
        migrations.DeleteModel(
            name='PostFollowCount',
        ),
        migrations.AddField(
            model_name='posttext',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.Post'),
        ),
        migrations.AddField(
            model_name='paylog',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object.Post'),
        ),
        migrations.AddField(
            model_name='paylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chargelog',
            name='charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object.Charge'),
        ),
        migrations.AddField(
            model_name='chargelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='solodatepay',
            unique_together={('solo', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='groupdatepay',
            unique_together={('group', 'date')},
        ),
    ]
