# Generated by Django 2.0.5 on 2018-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0009_auto_20181108_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='8cf144eb4afc432d8e22bb1872569f56', max_length=34, unique=True),
        ),
    ]
