# Generated by Django 2.0.5 on 2018-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0011_auto_20181110_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='amount',
            new_name='gross',
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='3e682c26de274b75b2a66d32e8346225', max_length=34, unique=True),
        ),
    ]
