# Generated by Django 2.0.5 on 2018-11-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0012_auto_20181112_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(default='9272516de61d429c8d9c26d63db61ecf', max_length=34, unique=True),
        ),
    ]
