# Generated by Django 2.0.5 on 2018-11-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0013_auto_20181112_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=34, null=True, unique=True),
        ),
    ]
