# Generated by Django 2.0.5 on 2018-11-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0015_auto_20181112_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupdatepay',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
