# Generated by Django 2.0.5 on 2018-11-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0016_auto_20181113_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object.Group')),
            ],
        ),
        migrations.CreateModel(
            name='SoloDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('solo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='object.Solo')),
            ],
        ),
        migrations.RemoveField(
            model_name='grouppost',
            name='group_date_pay',
        ),
        migrations.RemoveField(
            model_name='solopost',
            name='solo_date_pay',
        ),
        migrations.AlterField(
            model_name='grouppost',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.Post'),
        ),
        migrations.AlterField(
            model_name='solodatepay',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='solopost',
            name='post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.Post'),
        ),
        migrations.AddField(
            model_name='grouppost',
            name='group_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.GroupDate'),
        ),
        migrations.AddField(
            model_name='solopost',
            name='solo_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='object.SoloDate'),
        ),
        migrations.AlterUniqueTogether(
            name='solodate',
            unique_together={('solo', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='groupdate',
            unique_together={('group', 'date')},
        ),
    ]
