# Generated by Django 2.0.5 on 2018-11-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0017_auto_20181113_1516'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupdatepay',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='groupdatepay',
            name='group',
        ),
        migrations.AlterUniqueTogether(
            name='solodatepay',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='solodatepay',
            name='solo',
        ),
        migrations.DeleteModel(
            name='TestDec',
        ),
        migrations.DeleteModel(
            name='GroupDatePay',
        ),
        migrations.DeleteModel(
            name='SoloDatePay',
        ),
    ]
