# Generated by Django 2.0.5 on 2018-11-21 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_auto_20181120_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solofollow',
            name='solo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_solo_followed', to='object.Solo'),
        ),
    ]
